//https://en.wikipedia.org/wiki/Template:NFL_stadiums_map verify stadium names with this

let stadiums = [
  {name: "State Farm Stadium", team: `<a href="https://www.azcardinals.com/">Arizona Cardinals</a>`, city: `Glendale, Arizona`, capacity: `Capacity: 63,400`, location: {lat: 33.5276, lng: -112.2626}},
  {name: "Mercedes-Benz Stadium", team: `<a href="https://www.atlantafalcons.com/">Atlanta Falcons</a>`, city: `Atlanta, Georgia`, capacity: `Capacity: 71,000`, location: {lat: 33.7550, lng: -84.4008}},
  {name: "M&T Bank Stadium", team: `<a href="https://www.baltimoreravens.com/">Baltimore Ravens</a>`, city: `Baltimore, Maryland`, capacity: `Capacity: 71,008`, location: {lat: 39.2779, lng: -76.6228}},
  {name: "New Era Field", team: `<a href="https://www.buffalobills.com/">Buffalo Bills</a>`, city: `Orchard Park, New York`, capacity: `Capacity: 71,608`, location: {lat: 42.7740, lng: -78.7870}},
  {name: "Bank of America Stadium", team: `<a href="https://www.panthers.com/">Carolina Panthers</a>`, city: `Charlotte, North Carolina`, capacity: `Capacity: 75,523`, location: {lat: 35.2258, lng: -80.8528}},
  {name: "Soldier Field", team: `<a href="https://www.chicagobears.com/">Chicago Bears</a>`, city: `Chicago, Illinois`, capacity: `Capacity: 61,500`, location: {lat: 41.8623, lng: -87.6167}},
  {name: "Paul Brown Stadium", team: `<a href="https://www.bengals.com/">Cincinnati Bengals</a>`, city: `Cincinnati, Ohio`, capacity: `Capacity: 65,515`, location: {lat: 39.0955, lng: -84.5161}},
  {name: "FirstEnergy Stadium", team: `<a href="https://www.clevelandbrowns.com/">Cleveland Browns</a>`, city: `Cleveland, Ohio`, capacity: `Capacity: 67,895`, location: {lat: 41.5061, lng: -81.6997}},
  {name: "AT&T Stadium", team: `<a href="https://www.dallascowboys.com/">Dallas Cowboys</a>`, city: `Arlington, Texas`, capacity: `Capacity: 80,000`, location: {lat: 32.7473, lng: -97.0945}},
  {name: "Empower Field at Mile High", team: `<a href="https://www.denverbroncos.com/">Denver Broncos</a>`, city: `Denver, Colorado`, capacity: `Capacity: 76,125`, location: {lat: 39.7439, lng: -105.0201}},
  {name: "Ford Field", team: `<a href="https://www.detroitlions.com/">Detroit Lions</a>`, city: `Detroit, Michigan`, capacity: `Capacity: 65,000`, location: {lat: 42.3400, lng: -83.0456}},
  {name: "Lambeau Field", team: `<a href="https://www.packers.com/">Green Bay Packers</a>`, city: `Green Bay, Wisconsin`, capacity: `Capacity: 81,441`, location: {lat: 44.5013, lng: -88.062}},
  {name: "NRG Stadium", team: `<a href="https://www.houstontexans.com/">Houston Texans</a>`, city: `Houston, Texas`, capacity: `Capacity: 72,220`, location: {lat: 29.6847, lng: -95.4107}},
  {name: "Lucas Oil Stadium", team: `<a href="https://www.colts.com/">Indianapolis Colts</a>`, city: `Indianapolis, Indiana`, capacity: `Capacity: 67,000`, location: {lat: 39.7601, lng: -86.1639}},
  {name: "TIAA Bank Field", team: `<a href="https://www.jaguars.com/">Jacksonville Jaguars</a>`, city: `Jacksonville, Florida`, capacity: `Capacity: 69,132`, location: {lat: 30.3239, lng: -81.6373}},
  {name: "Arrowhead Stadium", team: `<a href="https://www.chiefs.com/">Kansas City Chiefs</a>`, city: `Kansas City, Missouri`, capacity: `Capacity: 76,416`, location: {lat: 39.0489, lng: -94.4839}},
  {name: "Allegiant Stadium", team: `<a href="https://www.raiders.com/">Las Vegas Raiders</a>`, city: `Paradise, Nevada`, capacity: `Capacity: 65,000`, location: {lat: 36.0908, lng: -115.1831}},
  {name: "SoFi Stadium", team: `<a href="https://www.chargers.com/">Los Angeles Chargers</a>`, city: `Inglewood, California`, capacity: `Capacity: 70,240`, location: {lat: 33.9534, lng: -118.2331}},
  {name: "SoFi Stadium", team: `<a href="https://www.therams.com/">Los Angeles Rams</a>`, city: `Inglewood, California`, capacity: `Capacity: 70,240`, location: {lat: 33.9534, lng: -118.2331}},
  {name: "Hard Rock Stadium", team: `<a href="https://www.miamidolphins.com/">Miami Dolphins</a>`, city: `Miami Gardens, Florida`, capacity: `Capacity: 65,326`, location: {lat: 25.9580, lng: -80.2388}},
  {name: "U.S. Bank Stadium", team: `<a href="https://www.vikings.com/">Minnesota Vikings</a>`, city: `Minneapolis, Minnesota`, capacity: `Capacity: 66,655`, location: {lat: 44.9740, lng: -93.2596}},
  {name: "Gillette Stadium", team: `<a href="https://www.patriots.com/">New England Patriots</a>`, city: `Foxborough, Massachusetts`, capacity: `Capacity: 66,829`, location: {lat: 42.0909, lng: -71.2643}},
  {name: "Mercedes-Benz Superdome", team: `<a href="https://www.neworleanssaints.com/">New Orleans Saints</a>`, city: `New Orleans, Louisiana`, capacity: `Capacity: 73,208`, location: {lat: 29.9511, lng: -90.0822}},
  {name: "MetLife Stadium", team: `<a href="https://www.giants.com/">New York Giants</a>`, city: `East Rutherford, New Jersey`, capacity: `Capacity: 82,500`, location: {lat: 40.8136, lng: -74.0743}},
  {name: "MetLife Stadium", team: `<a href="https://www.newyorkjets.com/">New York Jets</a>`, city: `East Rutherford, New Jersey`, capacity: `Capacity: 82,500`, location: {lat: 40.8136, lng: -74.0743}},
  {name: "Lincoln Financial Field", team: `<a href="https://www.philadelphiaeagles.com/">Philadelphia Eagles</a>`, city: `Philadelphia, Pennsylvania`, capacity: `Capacity: 69,596`, location: {lat: 39.9008, lng: -75.1675}},
  {name: "Heinz Field", team: `<a href="https://www.steelers.com/">Pittsburgh Steelers</a>`, city: `Pittsburgh, Pennsylvania`, capacity: `Capacity: 68,400`, location: {lat: 40.4468, lng: -80.0158}},
  {name: "Levi's Stadium", team: `<a href="https://www.49ers.com/">San Francisco 49ers</a>`, city: `Santa Clara, California`, capacity: `Capacity: 68,500`, location: {lat: 37.4030, lng: -121.9702}},
  {name: "Lumen Field", team: `<a href="https://www.seahawks.com/">Seattle Seahawks</a>`, city: `Seattle, Washington`, capacity: `Capacity: 69,000`, location: {lat: 47.5952, lng: -122.3316}},
  {name: "Raymond James Stadium", team: `<a href="https://www.buccaneers.com/">Tampa Bay Buccaneers</a>`, city: `Tampa, Florida`, capacity: `Capacity: 65,890`, location: {lat: 27.9759, lng: -82.5033}},
  {name: "Nissan Stadium", team: `<a href="https://www.tennesseetitans.com/">Tennessee Titans</a>`, city: `Nashville, Tennessee`, capacity: `Capacity: 69,143`, location: {lat: 36.1664, lng: -86.7713}},
  {name: "FedExField", team: `<a href="https://www.commanders.com/">Washington Commanders</a>`, city: `Landover, Maryland`, capacity: `Capacity: 82,000`, location: {lat: 38.9077, lng: -76.8644}}
  ]

  let teamStadiums = [
    {name: "State Farm Stadium", team: `<a href="https://www.azcardinals.com/">Arizona Cardinals</a>`, city: `Glendale, Arizona`, capacity: `Capacity: 63,400`, location: {lat: 33.5276, lng: -112.2626}},
    {name: "Mercedes-Benz Stadium", team: `<a href="https://www.atlantafalcons.com/">Atlanta Falcons</a>`, city: `Atlanta, Georgia`, capacity: `Capacity: 71,000`, location: {lat: 33.7550, lng: -84.4008}},
    {name: "M&T Bank Stadium", team: `<a href="https://www.baltimoreravens.com/">Baltimore Ravens</a>`, city: `Baltimore, Maryland`, capacity: `Capacity: 71,008`, location: {lat: 39.2779, lng: -76.6228}},
    {name: "New Era Field", team: `<a href="https://www.buffalobills.com/">Buffalo Bills</a>`, city: `Orchard Park, New York`, capacity: `Capacity: 71,608`, location: {lat: 42.7740, lng: -78.7870}},
    {name: "Bank of America Stadium", team: `<a href="https://www.panthers.com/">Carolina Panthers</a>`, city: `Charlotte, North Carolina`, capacity: `Capacity: 75,523`, location: {lat: 35.2258, lng: -80.8528}},
    {name: "Soldier Field", team: `<a href="https://www.chicagobears.com/">Chicago Bears</a>`, city: `Chicago, Illinois`, capacity: `Capacity: 61,500`, location: {lat: 41.8623, lng: -87.6167}},
    {name: "Paul Brown Stadium", team: `<a href="https://www.bengals.com/">Cincinnati Bengals</a>`, city: `Cincinnati, Ohio`, capacity: `Capacity: 65,515`, location: {lat: 39.0955, lng: -84.5161}},
    {name: "FirstEnergy Stadium", team: `<a href="https://www.clevelandbrowns.com/">Cleveland Browns</a>`, city: `Cleveland, Ohio`, capacity: `Capacity: 67,895`, location: {lat: 41.5061, lng: -81.6997}},
    {name: "AT&T Stadium", team: `<a href="https://www.dallascowboys.com/">Dallas Cowboys</a>`, city: `Arlington, Texas`, capacity: `Capacity: 80,000`, location: {lat: 32.7473, lng: -97.0945}},
    {name: "Empower Field at Mile High", team: `<a href="https://www.denverbroncos.com/">Denver Broncos</a>`, city: `Denver, Colorado`, capacity: `Capacity: 76,125`, location: {lat: 39.7439, lng: -105.0201}},
    {name: "Ford Field", team: `<a href="https://www.detroitlions.com/">Detroit Lions</a>`, city: `Detroit, Michigan`, capacity: `Capacity: 65,000`, location: {lat: 42.3400, lng: -83.0456}},
    {name: "Lambeau Field", team: `<a href="https://www.packers.com/">Green Bay Packers</a>`, city: `Green Bay, Wisconsin`, capacity: `Capacity: 81,441`, location: {lat: 44.5013, lng: -88.062}},
    {name: "NRG Stadium", team: `<a href="https://www.houstontexans.com/">Houston Texans</a>`, city: `Houston, Texas`, capacity: `Capacity: 72,220`, location: {lat: 29.6847, lng: -95.4107}},
    {name: "Lucas Oil Stadium", team: `<a href="https://www.colts.com/">Indianapolis Colts</a>`, city: `Indianapolis, Indiana`, capacity: `Capacity: 67,000`, location: {lat: 39.7601, lng: -86.1639}},
    {name: "TIAA Bank Field", team: `<a href="https://www.jaguars.com/">Jacksonville Jaguars</a>`, city: `Jacksonville, Florida`, capacity: `Capacity: 69,132`, location: {lat: 30.3239, lng: -81.6373}},
    {name: "Arrowhead Stadium", team: `<a href="https://www.chiefs.com/">Kansas City Chiefs</a>`, city: `Kansas City, Missouri`, capacity: `Capacity: 76,416`, location: {lat: 39.0489, lng: -94.4839}},
    {name: "Allegiant Stadium", team: `<a href="https://www.raiders.com/">Las Vegas Raiders</a>`, city: `Paradise, Nevada`, capacity: `Capacity: 65,000`, location: {lat: 36.0908, lng: -115.1831}},
    {name: "SoFi Stadium", team: `<a href="https://www.chargers.com/">Los Angeles Chargers</a>`, city: `Inglewood, California`, capacity: `Capacity: 70,240`, location: {lat: 33.9534, lng: -118.2331}},
    {name: "SoFi Stadium", team: `<a href="https://www.therams.com/">Los Angeles Rams</a>`, city: `Inglewood, California`, capacity: `Capacity: 70,240`, location: {lat: 33.9534, lng: -118.2331}},
    {name: "Hard Rock Stadium", team: `<a href="https://www.miamidolphins.com/">Miami Dolphins</a>`, city: `Miami Gardens, Florida`, capacity: `Capacity: 65,326`, location: {lat: 25.9580, lng: -80.2388}},
    {name: "U.S. Bank Stadium", team: `<a href="https://www.vikings.com/">Minnesota Vikings</a>`, city: `Minneapolis, Minnesota`, capacity: `Capacity: 66,655`, location: {lat: 44.9740, lng: -93.2596}},
    {name: "Gillette Stadium", team: `<a href="https://www.patriots.com/">New England Patriots</a>`, city: `Foxborough, Massachusetts`, capacity: `Capacity: 66,829`, location: {lat: 42.0909, lng: -71.2643}},
    {name: "Mercedes-Benz Superdome", team: `<a href="https://www.neworleanssaints.com/">New Orleans Saints</a>`, city: `New Orleans, Louisiana`, capacity: `Capacity: 73,208`, location: {lat: 29.9511, lng: -90.0822}},
    {name: "MetLife Stadium", team: `<a href="https://www.giants.com/">New York Giants</a>`, city: `East Rutherford, New Jersey`, capacity: `Capacity: 82,500`, location: {lat: 40.8136, lng: -74.0743}},
    {name: "MetLife Stadium", team: `<a href="https://www.newyorkjets.com/">New York Jets</a>`, city: `East Rutherford, New Jersey`, capacity: `Capacity: 82,500`, location: {lat: 40.8136, lng: -74.0743}},
    {name: "Lincoln Financial Field", team: `<a href="https://www.philadelphiaeagles.com/">Philadelphia Eagles</a>`, city: `Philadelphia, Pennsylvania`, capacity: `Capacity: 69,596`, location: {lat: 39.9008, lng: -75.1675}},
    {name: "Heinz Field", team: `<a href="https://www.steelers.com/">Pittsburgh Steelers</a>`, city: `Pittsburgh, Pennsylvania`, capacity: `Capacity: 68,400`, location: {lat: 40.4468, lng: -80.0158}},
    {name: "Levi's Stadium", team: `<a href="https://www.49ers.com/">San Francisco 49ers</a>`, city: `Santa Clara, California`, capacity: `Capacity: 68,500`, location: {lat: 37.4030, lng: -121.9702}},
    {name: "Lumen Field", team: `<a href="https://www.seahawks.com/">Seattle Seahawks</a>`, city: `Seattle, Washington`, capacity: `Capacity: 69,000`, location: {lat: 47.5952, lng: -122.3316}},
    {name: "Raymond James Stadium", team: `<a href="https://www.buccaneers.com/">Tampa Bay Buccaneers</a>`, city: `Tampa, Florida`, capacity: `Capacity: 65,890`, location: {lat: 27.9759, lng: -82.5033}},
    {name: "Nissan Stadium", team: `<a href="https://www.tennesseetitans.com/">Tennessee Titans</a>`, city: `Nashville, Tennessee`, capacity: `Capacity: 69,143`, location: {lat: 36.1664, lng: -86.7713}},
    {name: "FedExField", team: `<a href="https://www.commanders.com/">Washington Commanders</a>`, city: `Landover, Maryland`, capacity: `Capacity: 82,000`, location: {lat: 38.9077, lng: -76.8644}}
    ]

let originalStadiums = [
    {name: "SoFi Stadium", team: "Los Angeles Chargers", location: {lat: 33.9534, lng: -118.2331}},
    {name: "Allegiant Stadium", team: "Las Vegas Raiders", location: {lat: 36.0908, lng: -115.1831}},
    {name: "FedExField", team: "Washington Commanders", location: {lat: 38.9077, lng: -76.8644}},
    {name: "Lincoln Financial Field", team: "Philadelphia Eagles", location: {lat: 39.9008, lng: -75.1675}},
    {name: "M&T Bank Stadium", team: "Baltimore Ravens", location: {lat: 39.2779, lng: -76.6228}},
    {name: "Mercedes-Benz Superdome", team: "New Orleans Saints", location: {lat: 29.9511, lng: -90.0822}},
    {name: "MetLife Stadium", team: "New York Giants/New York Jets", location: {lat: 40.8136, lng: -74.0743}},
    {name: "Nissan Stadium", team: "Tennessee Titans", location: {lat: 36.1664, lng: -86.7713}},
    {name: "Paul Brown Stadium", team: "Cincinnati Bengals", location: {lat: 39.0955, lng: -84.5161}},
    {name: "Raymond James Stadium", team: "Tampa Bay Buccaneers", location: {lat: 27.9759, lng: -82.5033}},
    {name: "SoFi Stadium", team: "Los Angeles Rams", location: {lat: 33.9534, lng: -118.2331}},
    {name: "Soldier Field", team: "Chicago Bears", location: {lat: 41.8623, lng: -87.6167}},
    {name: "State Farm Stadium", team: "Arizona Cardinals", location: {lat: 33.5276, lng: -112.2626}},
    {name: "TIAA Bank Field", team: "Jacksonville Jaguars", location: {lat: 30.3239, lng: -81.6373}},
    {name: "U.S. Bank Stadium", team: "Minnesota Vikings", location: {lat: 44.9740, lng: -93.2596}},
    {name: "Empower Field at Mile High", team: "Denver Broncos", location: {lat: 39.7439, lng: -105.0201}},
    {name: "Gillette Stadium", team: "New England Patriots", location: {lat: 42.0909, lng: -71.2643}},
    {name: "Hard Rock Stadium", team: "Miami Dolphins", location: {lat: 25.9580, lng: -80.2388}},
    {name: "Heinz Field", team: "Pittsburgh Steelers", location: {lat: 40.4468, lng: -80.0158}},
    {name: "Lambeau Field", team: "Green Bay Packers", location: {lat: 44.5013, lng: -88.062}},
    {name: "Levi's Stadium", team: "San Francisco 49ers", location: {lat: 37.4030, lng: -121.9702}},
    {name: "Lumen Field", team: "Seattle Seahawks", location: {lat: 47.5952, lng: -122.3316}},
    {name: "Lucas Oil Stadium", team: "Indianapolis Colts", location: {lat: 39.7601, lng: -86.1639}},
    {name: "M&T Bank Stadium", team: "Buffalo Bills", location: {lat: 42.7738, lng: -78.7870}},
    {name: "MetLife Stadium", team: "New York Jets/New York Giants", location: {lat: 40.8136, lng: -74.0743}},
    {name: "Nissan Stadium", team: "Houston Texans", location: {lat: 29.6847, lng: -95.4107}},
    {name: "SoFi Stadium", team: "Los Angeles Chargers", location: {lat: 33.9534, lng: -118.2331}},
    {name: "State Farm Stadium", team: "Los Angeles Rams", location: {lat: 33.5276, lng: -112.2626}},
    {name: "TIAA Bank Field", team: "Tampa Bay Buccaneers", location: {lat: 30.3239, lng: -81.6373}},
    {name: "FirstEnergy Stadium", team: "Cleveland Browns", location: {lat: 41.5061, lng: -81.6997}},
    {name: "Arrowhead Stadium", team: "Kansas City Chiefs", location: {lat: 39.0489, lng: -94.4839}},
    {name: "AT&T Stadium", team: "Dallas Cowboys", location: {lat: 32.7473, lng: -97.0945}},
    {name: "Bank of America Stadium", team: "Carolina Panthers", location: {lat: 35.2258, lng: -80.8528}},
    {name: "Ford Field", team: "Detroit Lions", location: {lat: 42.3400, lng: -83.0456}},
    {name: "New Era Field", team: "Buffalo Bills", location: {lat: 42.7740, lng: -78.7870}},
    {name: "NRG Stadium", team: "Houston Texans", location: {lat: 29.6847, lng: -95.4107}},
    {name: "Paul Brown Stadium", team: "Cincinnati Bengals", location: {lat: 39.0955, lng: -84.5161}},
    {name: "RingCentral Coliseum", team: "Oakland Raiders", location: {lat: 37.7516, lng: -122.2005}},
    {name: "SoFi Stadium", team: "Los Angeles Chargers", location: {lat: 33.9534, lng: -118.2331}},
    {name: "U.S. Bank Stadium", team: "Minnesota Vikings", location: {lat: 44.9740, lng: -93.2596}},
    {name: "CenturyLink Field", team: "Seattle Seahawks", location: {lat: 47.5952, lng: -122.3316}},
    {name: "Mercedes-Benz Stadium", team: "Atlanta Falcons", location: {lat: 33.7550, lng: -84.4008}}
  ]